name: Release XCFramework
on: workflow_dispatch

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r .scripts/requirements.txt
      - run: python .scripts/release.py ${{ secrets.TOKEN }} ${{ github.ref_name }}
